### ISSUE TITLE
version 1.0.10 isn't on npm

### ISSUE THREAD

**Issue by OfekA** [geolonia/mbgl-gesture-handling#4]
Is there a reason why the version with the fullscreen fixes (1.0.10) isn't on npm yet?

Thanks a lot for creating this plugin!

**Comment by kamataryo** [comment]
@OfekA Hi, thanks for the interest in the package!
The package has been renamed from [`@tilecloud/mbgl-gesture-handling`](https://www.npmjs.com/package/@tilecloud/mbgl-gesture-handling) into [`@geolonia/mbgl-gesture-handling`](https://www.npmjs.com/package/@geolonia/mbgl-gesture-handling) and the latest version 1.0.11 we have just shipped also includes the fix for the fullscreen problem.
Please try with `npm install @geolonia/mbgl-gesture-handling -S`.

**Comment by OfekA** [comment]
Thanks, appreciate it!

**Comment by miya0001** [comment]
@OfekA @kamataryo 

There will be some conflicts with following PR.
https://github.com/mapbox/mapbox-gl-js/pull/9365

We have to consider another solution...

Thanks 😊
